name: Docker Image CI
on: workflow_dispatch
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
           name: Login to DockerHub
         - uses: docker/login-action@v3
           with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
         - name: Build the Docker image
           run: docker build . --file Dockerfile --tag adelongnsw/api:${{ github.sha }}
         - name: Deploy docker image to docker hub
           run: docker push adelongnsw/api:${{ github.sha }}
