name: Docker Image CI
on: workflow_dispatch
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - name: Docker login
           env:
              DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
              DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
           run: |
              docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
         - name: Build the Docker image
           run: docker build . --file Dockerfile --tag adelongnsw/api:${{ github.sha }}
         - name: Deploy docker image to docker hub
           run: docker push adelongnsw/api:${{ github.sha }}
